### ISSUE TITLE
Message/Group Chat Page

### ISSUE THREAD

**Issue by Said-laasri** [Talckatoo/talckatoo_react_native#8]
Using Figma : https://www.figma.com/file/tvWJWYrJW9OgGaEPtxF6Ai/Talkato-Portfolio?type=design&node-id=0-1&mode=design&t=78Iwxa2T8qwSFqAI-0

![Image](https://github.com/Talckatoo/talckatoo_react_native/assets/100702612/ce4bc5e4-9567-473e-a6e6-6aed8ae3dad8)

**Comment by Miminiverse** [comment]
Done
